# Makefile

CC = gcc

CFLAGS = -std=c99 -D_GNU_SOURCE -Wall

all: findmagics knight_castling notlinboard ep_squares

findmagics: findmagics.c

knight_castling: knight_castling.c

notlinboard: notlinboard.c

ep_squares: ep_squares.c

clean:
	rm -f findmagics knight_castling notlinboard ep_squares
